<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="<?=$charset;?>">
    <meta ="<?=$charset;?>">
    <title><?=$title;?></title>
    <meta name="description" content="<?=$description;?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="/bower_components/jquery/dist/jquery.slim.min.js"></script>

    <!-- Styles -->
    <link rel="stylesheet" href="/bower_components/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/build/dist/main.min.css">
    <!-- /Styles -->

</head>
<body>

<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#"><em class="fa fa-rocket"> SIMPLE QUIZZ</em></a>
</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a class="nav-link" href="?">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="?controller=quiz&action=create">Create Quiz</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="?controller=quiz&action=list">List of the quizzes</a>
                </li>
            </ul>
        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
            <h4><?=$title;?></h4>
            <section class="placeholders">
                <?=$template;?>
            </section>
            <footer class="footer">
                <div class="container">
                    <span class="text-muted">
                        &copy; Stanislav WEB &lt;stanisov@gmail.com&gt;
                    </span>
                </div>
            </footer>
        </main>
    </div>
</div>
<!-- Optional JavaScript -->
<script src="/bower_components/tether/dist/js/tether.min.js"></script>
<!--<script src="/bower_components/popper.js/dist/umd/popper.min.js"></script>-->
<script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="/build/dist/main.min.js"></script>
<script>
    jQuery(document).ready(function() {
        Main.init();
    });
</script>
<!-- /Optional JavaScript -->
</body>
</html>