<?php if(true === isset($message)): ?>
    <div class="alert alert-<?=$status;?>" role="alert">
        <?=$message;?>
    </div>
<?php endif; ?>
<form method="POST">
    <div class="form-group">
        <label for="name">Quiz name</label>
        <input class="form-control"
               id="name"
               name="name"
               placeholder="Enter quiz name"
               required
        >
    </div>
    <div class="form-group">
        <label for="name">Description</label>
        <textarea class="form-control"
               id="description"
               name="description"
               placeholder="Short description (optional)"></textarea>
    </div>
    <button class="btn btn-primary">Create quiz</button>
</form>