<?php if(true === isset($message)): ?>
    <!-- Alert message -->
    <div class="alert alert-<?=$status;?>" role="alert">
        <?=$message;?>
    </div>
    <!-- /Alert message -->
<?php endif; ?>
<?php if(false === empty($quizList)): ?>
    <!-- Section list -->
    <div id="accordion" role="tablist">
        <?php
        /** @var \Quiz\Modules\Question\Entities\Quiz $quiz */
        ?>
        <?php /** @noinspection ForeachSourceInspection */
        foreach ($quizList as $quiz): ?>
        <div class="card">
            <div class="card-header" role="tab" id="heading-<?=$quiz->id;?>">
                <div class="mb-0">
                    <a data-toggle="collapse"
                       data-parent="#accordion"
                       href="#collapse-<?=$quiz->id;?>"
                       aria-expanded="false"
                       aria-controls="collapse-<?=$quiz->id;?>"
                       class="collapsed">
                        <i class="fa fa-file-text-o"></i>
                        <span><?=$quiz->name;?></span>
                    </a><b class="badge badge-default badge-pill"><?=$quiz->count;?></b>
                </div>
            </div>
            <div id="collapse-<?=$quiz->id;?>"
                 class="collapse"
                 role="tabpanel"
                 aria-labelledby="heading-<?=$quiz->id;?>"
                 aria-expanded="false" style="">
                <div class="fetch long">
                    <?=$quiz->description;?>
                    <div class="btn-toolbar mb-3" role="toolbar">
                        <?php
                        $disabled = (1 > $quiz->count
                            || (
                                $quiz->status === \Quiz\Modules\Question\QuizModuleService::STATUS_PROGRESS
                                || $quiz->status === \Quiz\Modules\Question\QuizModuleService::STATUS_DONE));
                        ?>
                        <button onclick="<?= $disabled ? 'return false;' : 'Modal.confirmDialog(event)';?>"
                                id="take"
                                class="btn btn-primary btn-success take <?= $disabled ? 'disabled' : '';?>"
                                data-toggle="modal"
                                data-target="<?= $disabled ? '' : '#confirm-delete';?>"
                                data-title="Start # <?=$quiz->id;?>"
                                data-description="Do you ready to take this quiz?"
                                data-href="?controller=passing&quiz_id=<?=$quiz->id;?>"
                                data-original-title="Take the quiz!">
                            Take the quiz!
                        </button>
                        <div class="btn-group btn-group-justified" role="group">
                            <div class="btn-group" role="group">
                                <a href="?controller=question&action=list&quiz_id=<?=$quiz->id;?>" id="edit"
                                        class="btn btn-success"
                                        data-original-title="Edit">
                                    <i class="fa fa-pencil-square-o fa-lg"
                                    ></i>
                                </a>
                            </div>
                            <div class="btn-group" role="group">
                                <button onclick="Modal.confirmDialog(event)"
                                        id="delete"
                                        class="btn btn-warning"
                                        data-toggle="modal"
                                        data-target="#confirm-delete"
                                        data-title="Delete # <?=$quiz->id;?>"
                                        data-description="Are you sure to drop this quiz ? All question will be removed by reference too"
                                        data-href="?controller=quiz&action=delete&id=<?=$quiz->id;?>"
                                        data-original-title="Delete">
                                    <i class="fa fa-trash-o fa-lg"
                                    ></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
    <!-- /Section list -->

    <!-- Modal dialog -->
    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button"
                            class="btn btn-default"
                            data-dismiss="modal">Cancel</button>
                    <a class="btn btn-danger btn-ok">Ok</a>
                </div>
            </div>
        </div>
    </div>
    <!-- /Modal dialog -->
<?php else: ?>
    <div class="alert alert-warning" role="alert">
        List empty. Please create at least one quiz.
    </div>
<?php endif;?>