<?php if(true === isset($message)): ?>
    <!-- Alert message -->
    <div class="alert alert-<?=$status;?>" role="alert">
        <?=$message;?>
    </div>
    <!-- /Alert message -->
<?php endif; ?>
<?php if(false === empty($quizList)): ?>
    <!-- Section list -->
    <div id="accordion" role="tablist" aria-multiselectable="true">
        <?php
        /** @var \Quiz\Modules\Question\Entities\Quiz $quiz */
        ?>
        <?php foreach ($quizList as $quiz): ?>
        <div class="card">
            <div class="card-header" role="tab" id="heading-<?=$quiz->id;?>">
                <div class="mb-0">
                    <a data-toggle="collapse"
                       data-parent="#accordion"
                       href="#collapse-<?=$quiz->id;?>"
                       aria-expanded="false"
                       aria-controls="collapse-<?=$quiz->id;?>"
                       class="collapsed">
                        <i class="fa fa-file-text-o" aria-hidden="true"></i>
                        <span><?=$quiz->name;?></span>
                    </a><b class="badge badge-default badge-pill"><?=$quiz->count;?></b>
                </div>
            </div>
            <div id="collapse-<?=$quiz->id;?>"
                 class="collapse"
                 role="tabpanel"
                 aria-labelledby="heading-<?=$quiz->id;?>"
                 aria-expanded="false" style="">
                <div class="card-block long">
                    <?=$quiz->description;?>
                    <div class="btn-toolbar mb-3" role="toolbar">
                        <div class="btn-group btn-group-justified" role="group">
                            <div class="btn-group" role="group">
                                <button id="take"
                                        class="btn btn-primary btn-success take <?=(1 > $quiz->count) ? 'disabled' : '';?>"
                                        data-original-title="Take the quiz!">
                                    Take the quiz!
                                </button>
                            </div>
                            <div class="btn-group" role="group">
                                <button onclick="Modal.confirmDialog(event)"
                                        id="delete"
                                        class="btn btn-warning"
                                        data-toggle="modal"
                                        data-target="#confirm-delete"
                                        data-title="Delete # <?=$quiz->id;?>"
                                        data-description="Are you sure to drop this quiz ? All question will be removed by reference too"
                                        data-href="?controller=quiz&action=delete&id=<?=$quiz->id;?>"
                                        data-original-title="Delete">
                                    <i class="fa fa-trash-o fa-lg"
                                       aria-hidden="true"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <div class="alert alert-warning" role="alert">
        List empty. Please create at least one quiz.
    </div>
<?php endif;?>
<!-- /Section list -->

<!-- Modal dialog -->
<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button"
                        class="btn btn-default"
                        data-dismiss="modal">Cancel</button>
                <a class="btn btn-danger btn-ok">Delete</a>
            </div>
        </div>
    </div>
</div>
<!-- /Modal dialog -->