<?php if(true === isset($message)): ?>
    <!-- Alert message -->
    <div class="alert alert-<?=$status;?>" role="alert">
        <?=$message;?>
    </div>
    <!-- /Alert message -->
<?php endif; ?>
<?php
/** @var \Quiz\Modules\Question\Entities\Quiz $quiz */
?>
<?php if(true === isset($quiz->id)): ?>
    <div class="bs-callout bs-callout-warning">
        <h4><?=$quiz->name;?> (<?=$quiz->count;?> / <?=$config->quiz['quiz_limit'];?>)</h4>
        <p><?=$quiz->description;?></p>
    </div>
    <!-- Section list -->
    <div id="accordion" role="tablist" aria-multiselectable="true">
        <?php foreach ($quizList as $quiz): ?>
            <div class="card">
                <div class="card-header" role="tab" id="heading-<?=$quiz->id;?>">
                    <div class="mb-0">
                        <a data-toggle="collapse"
                           data-parent="#accordion"
                           href="#collapse-<?=$quiz->id;?>"
                           aria-expanded="false"
                           aria-controls="collapse-<?=$quiz->id;?>"
                           class="collapsed">
                            <i class="fa fa-file-text-o" aria-hidden="true"></i>
                            <span><?=$quiz->name;?></span>
                        </a><b class="badge badge-default badge-pill"><?=$quiz->count;?></b>
                    </div>
                </div>
                <div id="collapse-<?=$quiz->id;?>"
                     class="collapse"
                     role="tabpanel"
                     aria-labelledby="heading-<?=$quiz->id;?>"
                     aria-expanded="false" style="">
                    <div class="card-block long">
                        <?=$quiz->description;?>
                        <div class="btn-toolbar mb-3" role="toolbar">
                            <button type="button"
                                    class="btn btn-secondary btn-success <?=(1 > $quiz->count) ? 'disabled' : '';?>">
                                Take the quiz!</button>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <div class="alert alert-warning" role="alert">
        Perhaps you have a wrong section or there are no questions yet
    </div>
<?php endif;?>
<!-- /Section list -->

<!-- Toolbar -->
<section class="content">
    <h1>Table Filter</h1>
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="">
                <div class="filter">
                    <div class="btn-group">
                        <button type="button" class="btn btn-success btn-filter" data-target="pagado">Pagado</button>
                        <button type="button" class="btn btn-warning btn-filter" data-target="pendiente">Pendiente</button>
                        <button type="button" class="btn btn-danger btn-filter" data-target="cancelado">Cancelado</button>
                        <button type="button" class="btn btn-default btn-filter" data-target="all">Todos</button>
                    </div>
                </div>
                <div class="table-container">
                    <table class="table table-filter">
                        <tbody>
                        <tr data-status="pagado">
                            <td>
                                <div class="ckbox">
                                    <input type="checkbox" id="checkbox1">
                                    <label for="checkbox1"></label>
                                </div>
                            </td>
                            <td>
                                <a href="javascript:;" class="star">
                                    <i class="glyphicon glyphicon-star"></i>
                                </a>
                            </td>
                            <td>
                                <div class="media">
                                    <a href="#" class="pull-left">
                                        <img src="https://s3.amazonaws.com/uifaces/faces/twitter/fffabs/128.jpg" class="media-photo">
                                    </a>
                                    <div class="media-body">
                                        <span class="media-meta pull-right">Febrero 13, 2016</span>
                                        <h4 class="title">
                                            Lorem Impsum
                                            <span class="pull-right pagado">(Pagado)</span>
                                        </h4>
                                        <p class="summary">Ut enim ad minim veniam, quis nostrud exercitation...</p>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr data-status="pendiente">
                            <td>
                                <div class="ckbox">
                                    <input type="checkbox" id="checkbox3">
                                    <label for="checkbox3"></label>
                                </div>
                            </td>
                            <td>
                                <a href="javascript:;" class="star">
                                    <i class="glyphicon glyphicon-star"></i>
                                </a>
                            </td>
                            <td>
                                <div class="media">
                                    <a href="#" class="pull-left">
                                        <img src="https://s3.amazonaws.com/uifaces/faces/twitter/fffabs/128.jpg" class="media-photo">
                                    </a>
                                    <div class="media-body">
                                        <span class="media-meta pull-right">Febrero 13, 2016</span>
                                        <h4 class="title">
                                            Lorem Impsum
                                            <span class="pull-right pendiente">(Pendiente)</span>
                                        </h4>
                                        <p class="summary">Ut enim ad minim veniam, quis nostrud exercitation...</p>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr data-status="cancelado">
                            <td>
                                <div class="ckbox">
                                    <input type="checkbox" id="checkbox2">
                                    <label for="checkbox2"></label>
                                </div>
                            </td>
                            <td>
                                <a href="javascript:;" class="star">
                                    <i class="glyphicon glyphicon-star"></i>
                                </a>
                            </td>
                            <td>
                                <div class="media">
                                    <a href="#" class="pull-left">
                                        <img src="https://s3.amazonaws.com/uifaces/faces/twitter/fffabs/128.jpg" class="media-photo">
                                    </a>
                                    <div class="media-body">
                                        <span class="media-meta pull-right">Febrero 13, 2016</span>
                                        <h4 class="title">
                                            Lorem Impsum
                                            <span class="pull-right cancelado">(Cancelado)</span>
                                        </h4>
                                        <p class="summary">Ut enim ad minim veniam, quis nostrud exercitation...</p>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr data-status="pagado" class="selected">
                            <td>
                                <div class="ckbox">
                                    <input type="checkbox" id="checkbox4" checked>
                                    <label for="checkbox4"></label>
                                </div>
                            </td>
                            <td>
                                <a href="javascript:;" class="star star-checked">
                                    <i class="glyphicon glyphicon-star"></i>
                                </a>
                            </td>
                            <td>
                                <div class="media">
                                    <a href="#" class="pull-left">
                                        <img src="https://s3.amazonaws.com/uifaces/faces/twitter/fffabs/128.jpg" class="media-photo">
                                    </a>
                                    <div class="media-body">
                                        <span class="media-meta pull-right">Febrero 13, 2016</span>
                                        <h4 class="title">
                                            Lorem Impsum
                                            <span class="pull-right pagado">(Pagado)</span>
                                        </h4>
                                        <p class="summary">Ut enim ad minim veniam, quis nostrud exercitation...</p>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr data-status="pendiente">
                            <td>
                                <div class="ckbox">
                                    <input type="checkbox" id="checkbox5">
                                    <label for="checkbox5"></label>
                                </div>
                            </td>
                            <td>
                                <a href="javascript:;" class="star">
                                    <i class="glyphicon glyphicon-star"></i>
                                </a>
                            </td>
                            <td>
                                <div class="media">
                                    <a href="#" class="pull-left">
                                        <img src="https://s3.amazonaws.com/uifaces/faces/twitter/fffabs/128.jpg" class="media-photo">
                                    </a>
                                    <div class="media-body">
                                        <span class="media-meta pull-right">Febrero 13, 2016</span>
                                        <h4 class="title">
                                            Lorem Impsum
                                            <span class="pull-right pendiente">(Pendiente)</span>
                                        </h4>
                                        <p class="summary">Ut enim ad minim veniam, quis nostrud exercitation...</p>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
<!-- Toolbar -->

        <script>
            jQuery(function() {
                $('.star').on('click', function () {
                    $(this).toggleClass('star-checked');
                });

                $('.ckbox label').on('click', function () {
                    $(this).parents('tr').toggleClass('selected');
                });

                $('.btn-filter').on('click', function () {
                    var $target = $(this).data('target');
                    if ($target != 'all') {
                        $('.table tr').css('display', 'none');
                        $('.table tr[data-status="' + $target + '"]').hide().fadeIn('slow');
                    } else {
                        $('.table tr').css('display', 'none').hide().fadeIn('slow');
                    }
                });
            });

        </script>
<!-- Modal dialog -->
<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            </div>
            <div class="modal-body">
                <div class="control-group" id="fields">
                    <label class="control-label" for="field1">Nice Multiple Form Fields</label>
                    <div class="controls">
                        <form role="form" autocomplete="off">
                            <div class="entry input-group col-xs-3">
                                <input class="form-control" name="fields[]" type="text" placeholder="Type something" />
                                <span class="input-group-btn">
                            <button class="btn btn-success btn-add" type="button">
                                <span class="glyphicon glyphicon-plus"></span>
                            </button>
                        </span>
                            </div>
                        </form>
                        <br>
                        <small>Press <span class="glyphicon glyphicon-plus gs"></span> to add another form field :)</small>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button"
                        class="btn btn-default"
                        data-dismiss="modal">Cancel</button>
                <a class="btn btn-danger btn-ok">Ok</a>
            </div>
        </div>
    </div>
</div>
<!-- /Modal dialog -->
<div class="row">

</div>
<script>
    $(function()
    {
        $(document).on('click', '.btn-add', function(e)
        {
            e.preventDefault();

            var controlForm = $('.controls form:first'),
                currentEntry = $(this).parents('.entry:first'),
                newEntry = $(currentEntry.clone()).appendTo(controlForm);

            newEntry.find('input').val('');
            controlForm.find('.entry:not(:last) .btn-add')
                .removeClass('btn-add').addClass('btn-remove')
                .removeClass('btn-success').addClass('btn-danger')
                .html('<span class="glyphicon glyphicon-minus"></span>');
        }).on('click', '.btn-remove', function(e)
        {
            $(this).parents('.entry:first').remove();

            e.preventDefault();
            return false;
        });
    });

</script>