<?php
use \Quiz\Modules\Question\QuestionModuleService;
?>
<?php if(true === isset($message)): ?>
    <!-- Alert message -->
    <div class="alert alert-<?=$status;?>" role="alert">
        <?=$message;?>
    </div>
    <!-- /Alert message -->
<?php endif; ?>
<?php
/** @var \Quiz\Modules\Question\Entities\Quiz $quiz */
?>
<?php if(null !== $quiz->id): ?>
    <!-- Quiz title -->
    <div class="row">
        <div class="col">
            <strong><?=$quiz->name;?> (<?=$quiz->count;?> / <?=$config->quiz['quiz_limit'];?>)</strong>
            <?=$quiz->description;?>
        </div>
    </div>
    <!-- /Quiz title -->

    <!-- Toolbar -->
    <div class="btn-group btn-group-sm question-toolbar" role="group" aria-label="Questions toolbar">
        <?php if(false === empty($questionsList)): ?>
        <div class="btn-group pull-right" data-toggle="buttons-radio">
                <button id="collapse-init" class="btn btn-primary">
                    Expand all
                </button>
        </div>
        <?php endif;?>
        <?php if(QuestionModuleService::STATUS_DONE !== $quiz->status): ?>
        <div class="btn-group" role="group" aria-label="Questions toolbar">
                <button type="button"
                        onclick="Modal.confirmDialog(event)"
                        class="btn btn-primary"
                        data-toggle="modal"
                        data-target="#add-quest"
                        data-original-title="Add question">Add question
                </button>
        </div>
        <?php endif;?>
    </div>
    <!-- /Toolbar -->

    <?php if(false === empty($questionsList)): ?>
        <!-- Search -->
        <form class="form-search">
            <input id="tableSearch" onkeyup="Filter.search()" placeholder="Search for questions" class="col-xs-2">
            <button class="btn btn-xs">Search</button>
        </form>
        <!-- /Search -->
        <!-- Section list -->
        <div id="accordion" role="tablist" class="panel-group">
            <table id="searchTable">
                <?php
                /** @var \Quiz\Modules\Question\DTO\QuestionsDataTransferObject $questionData */
                ?>
                <?php $i = 1;
                /** @noinspection ForeachSourceInspection */
                foreach ($questionsList as $questionData): ?>
                    <tr>
                        <td>
                            <div class="card">
                                <div class="card-header" role="tab" id="heading-<?=$questionData->getQuestion()->id;?>">
                                    <div class="mb-0">
                                        <a data-toggle="collapse"
                                           data-parent="#accordion"
                                           href="#collapse-<?=$questionData->getQuestion()->id;?>"
                                           aria-controls="collapse-<?=$questionData->getQuestion()->id;?>"
                                           class="collapsed">
                                            <i class="fa fa-file-text-o"></i>
                                            <span><b>Q:</b> <?=$questionData->getQuestion()->title;?></span>
                                        </a>
                                        <div class="btn-group" role="group">
                                            <?php if(QuestionModuleService::STATUS_DONE === $questionData->getQuestion()->status):?>
                                            <button class="btn btn-sm btn-success" disabled>
                                                <b><?=QuestionModuleService::STATUS_DONE?></b>
                                            </button>
                                            <?php elseif(QuestionModuleService::STATUS_PROGRESS === $questionData->getQuestion()->status): ?>
                                                <button class="btn btn-sm btn-primary" disabled>
                                                    <b><?=QuestionModuleService::STATUS_PROGRESS?></b>
                                                </button>
                                            <?php else: ?>
                                                <button class="btn btn-sm btn-primary" disabled>
                                                    <b><?=QuestionModuleService::STATUS_PENDING?></b>
                                                </button>
                                            <?php endif;?>
                                            <button onclick="Modal.confirmDialog(event)"
                                                    id="delete"
                                                    class="btn btn-warning"
                                                    data-toggle="modal"
                                                    data-target="#confirm-delete"
                                                    data-title="Delete # <?=$questionData->getQuestion()->id;?>"
                                                    data-description="Are you sure to drop this question ? All linked variants will be removed by reference too"
                                                    data-href="?controller=question&action=delete&quiz_id=<?=$quiz->id;?>&id=<?=$questionData->getQuestion()->id;?>"
                                                    data-original-title="Delete">
                                                <i class="fa fa-trash-o fa-lg"
                                                ></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <div id="collapse-<?=$questionData->getQuestion()->id;?>"
                                     role="tabpanel"
                                     class="collapse"
                                     aria-labelledby="heading-<?=$questionData->getQuestion()->id;?>"
                                     style="">
                                    <div class="fetch long">
                                        <ol>
                                            <?php foreach ($questionData->getQuestionVariants() as $questionVariant): ?>
                                                <li>
                                                    <?=$questionVariant->title;?>
                                                </li>
                                            <?php endforeach; ?>
                                        </ol>
                                   </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php $i++; endforeach; ?>
            </table>
        </div>
        <!-- /Section list -->

        <!-- Modal dialog -->
        <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button"
                                class="btn btn-default"
                                data-dismiss="modal">Cancel</button>
                        <a class="btn btn-danger btn-ok">Delete</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Modal dialog -->
    <?php else: ?>
        <div class="alert alert-warning" role="alert">
            List empty. Please create at least one question.
        </div>
    <?php endif;?>

    <!-- Modal dialog -->
    <div class="modal fade" id="add-quest" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <label class="control-label" for="field1">Add Question</label>
                    <small>Press <span class="fa fa-plus-square"></span> to add another variant</small>
                </div>
                <div class="modal-body">
                    <div class="alert alert-danger" id="modal-message" style="display:none;" role="alert">
                    </div>
                    <div class="control-group" id="fields">
                        <div class="controls">
                            <form action="?controller=question&action=create" method="POST" autocomplete="off">
                                <input type="hidden" name="quiz_id" value="<?=$quiz->id;?>">
                                <input type="hidden" name="answer" id="fun">
                                <div class="form-group">
                                    <textarea class="form-control"
                                              name="title"
                                              rows="5"
                                              maxlength="256"
                                              placeholder="Type question" required></textarea>
                                </div>
                                <p>Please type some answers for this question an choose one right</p>
                                <div class="input-group-btn form-field " id="radioBtn">
                                    <div class="entry input-group col-xs-3">
                                        <!-- Radio -->
                                        <a class="btn btn-success btn-sm active"  onclick="Form.radio(event,this);" data-toggle="fun" data-title="0">
                                        </a>
                                        <!-- /Radio -->
                                        <input class="form-control"
                                               name="variant[]"
                                               required />
                                        <span class="input-group-btn">
                                            <button class="btn btn-remove btn-danger" type="button">
                                                <span class="fa fa-minus-square"></span>
                                            </button>
                                        </span>
                                    </div>
                                    <div class="entry input-group col-xs-3">
                                        <!-- Radio -->
                                        <a class="btn btn-success btn-sm notActive" onclick="Form.radio(event,this);" data-toggle="fun" data-title="1">
                                        </a>
                                        <!-- /Radio -->
                                        <input class="form-control"
                                               name="variant[]"
                                               required />
                                        <span class="input-group-btn">
                                            <button class="btn btn-primary btn-add" type="button">
                                                <span class="fa fa-plus-square"></span>
                                            </button>
                                        </span>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button id="send"
                                            class="btn btn-primary">OK</button>
                                    <button type="button"
                                            class="btn btn-danger"
                                            data-dismiss="modal">Cancel</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /Modal dialog -->
<?php else: ?>
    <div class="alert alert-warning" role="alert">
        Perhaps you have a wrong section or there are no questions yet
    </div>
<?php endif;?>