<form method="POST">
    <div class="form-group">
        <label for="name">Quiz name</label>
        <input class="form-control"
               id="name"
               name="name"
               placeholder="Enter quiz name">
    </div>
    <div class="form-group">
        <label for="count">Quiz Count</label>
        <input type="number"
               class="form-control"
               id="count"
               name="count"
               min="1"
               max="30"
               placeholder="Enter max quiz count"
        >
    </div>
    <button class="btn btn-primary">Create quiz</button>
</form>