<div class="placeholder">
    <div class="list-group">
        <span class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">List of quizes (<?=count($quizList);?>)</h5>
            </div>
            <p class="mb-1">
                <?php if(false === empty($quizList)): ?>
                    <ul class="list-group">
                        <?php
                        /** @var \Quiz\Modules\Question\Entities\Quiz $quiz */
                        ?>
                        <?php foreach ($quizList as $quiz): ?>
                            <li class="list-group-item">
                                <?=$quiz->name;?> (<?=$quiz->count;?>)
                            </li>
                        <?php endforeach;?>
                    </ul>
                <?php else: ?>
                    List empty. Please create at least one quiz.
                <?php endif;?>
            </p>
        </span>
    </div>
</div>